# https://mangowm.github.io/docs/bindings

# misc
bind=super,escape,reload_config
bind=ctrl+alt,delete,quit

# main keybinds
bind=super,q,killclient,
bind=super,o,toggleoverview,
bind=super,f,togglemaximizescreen,
bind=super,m,togglefullscreen,
bind=super,grave,togglefloating,
bind=super,c,centerwin

# launch apps
bind=super,space,spawn,fuzzel
bind=super,return,spawn,footclient
bind=super,b,spawn,librewolf
bind=super,e,spawn,nautilus
bind=super,t,spawn,Telegram
bind=super,w,spawn,vscodium

# focus window
bind=super,h,focusdir,left
bind=super,l,focusdir,right
bind=super,k,focusdir,up
bind=super,j,focusdir,down
bind=alt,shift_l,focusstack,next

# move window
bind=super+shift,k,exchange_client,up
bind=super+shift,j,exchange_client,down
bind=super+shift,h,exchange_client,left
bind=super+shift,l,exchange_client,right

# resize window
bind=super+ctrl,k,resizewin,+0,-50
bind=super+ctrl,j,resizewin,+0,+50
bind=super+ctrl,h,resizewin,-50,+0
bind=super+ctrl,l,resizewin,+50,+0

# switch workspace
bind=super,1,view,1,0
bind=super,2,view,2,0
bind=super,3,view,3,0
bind=super,4,view,4,0
bind=super,5,view,5,0
bind=super,6,view,6,0
bind=super,7,view,7,0
bind=super,8,view,8,0
bind=super,9,view,9,0
bind=super,tab,viewtoright
bind=super+shift,tab,viewtoleft

# move active window in workspace
bind=super+shift,1,tag,1,0
bind=super+shift,2,tag,2,0
bind=super+shift,3,tag,3,0
bind=super+shift,4,tag,4,0
bind=super+shift,5,tag,5,0
bind=super+shift,6,tag,6,0
bind=super+shift,7,tag,7,0
bind=super+shift,8,tag,8,0
bind=super+shift,9,tag,9,0

# toggle view window in workspace
bind=super+ctrl,1,toggleview,1,0
bind=super+ctrl,2,toggleview,2,0
bind=super+ctrl,3,toggleview,3,0
bind=super+ctrl,4,toggleview,4,0
bind=super+ctrl,5,toggleview,5,0
bind=super+ctrl,6,toggleview,6,0
bind=super+ctrl,7,toggleview,7,0
bind=super+ctrl,8,toggleview,8,0
bind=super+ctrl,9,toggleview,9,0

# monitor actions
bind=alt,tab,focusmon,up
bind=alt+shift,tab,tagmon,up

# mouse binds
mousebind=super,btn_left,moveresize,curmove
mousebind=none,btn_middle,togglemaximizescreen,0
mousebind=super,btn_right,moveresize,curresize

# touchpad gestures
gesturebind=none,right,4,viewtoleft
gesturebind=none,left,4,viewtoright
gesturebind=none,up,4,toggleoverview
gesturebind=none,down,4,toggleoverview

# volume
bind=none,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=none,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# brightness
bind=none,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bind=none,XF86MonBrightnessDown,spawn,brightnessctl s 5%-
#bind=shift,XF86MonBrightnessUp,spawn,ddcutil  setvcp 10 + 20
#bind=shift,XF86MonBrightnessDown,spawn,ddcutil setvcp 10 - 20

# exec noctalia session menu
bind=super,s,spawn,qs -c noctalia-shell ipc call sessionMenu toggle

# captures fullscren and copies into clipboard
bind=none,print,spawn_shell,grim - | tee ~/Pictures/Screenshots/$(date +%Y-%m-%dT%H:%M:%S).png | wl-copy -t image/png
