# https://mangowm.github.io/docs

source = ./inputs.conf
source = ./binds.conf
source = ./layout.conf
source = ./misc.conf
source = ./exec.conf
source = ./visuals.conf
source = ./noctalia.conf

# monitors
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:75,x:0,y:0,scale:1,vrr:1
monitorrule=name:eDP-1,width:3072,height:1920,refresh:120,x:1280,y:1080,scale:2,vrr:1