# https://mangowm.github.io/docs/configuration/basics#autostart

exec-once=qs -c noctalia-shell
exec-once=foot --server
exec-once=Telegram -autostart

# https://mangowm.github.io/docs/configuration/xdg-portals#screen-sharing
exec-once=/usr/lib/xdg-desktop-portal-wlr

# https://mangowm.github.io/docs/quick-start#recommended-tools
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# https://github.com/mangowm/mango/wiki/monitors#using-xwayland-satellite-to-prevent-blurry-xwayland-apps
env=DISPLAY,:2
exec-once=xwayland-satellite :2
