# https://mangowm.github.io/docs/configuration/input

# keyboard
repeat_rate=40
repeat_delay=300
numlockon=1
xkb_rules_layout=us,ru
xkb_rules_options=grp:caps_toggle

# touchpad
tap_to_click=0
trackpad_natural_scrolling=1
click_method=2
trackpad_accel_speed=-0.2
swipe_min_threshold=40