# https://mangowm.github.io/docs/window-management

# workspaces
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# window rules
windowrule=tags:1,appid:footclient
windowrule=tags:2,appid:librewolf
windowrule=tags:3,appid:codium
windowrule=tags:4,appid:org.gnome.Nautilus
windowrule=tags:5,appid:org.telegram.desktop
windowrule=tags:6,appid:TrueConf
windowrule=tags:8,appid:YandexMusic
windowrule=tags:9,isfloating:1,appid:AmneziaVPN
