# https://mangowm.github.io/docs/configuration/miscellaneous

sloppyfocus=0 # focus follows the mouse cursor
warpcursor=1 # warp the cursor to the center of the window when focus changes via keyboard
cursor_hide_timeout=2 # hide the cursor after n seconds of inactivity (0 to disable)
enable_hotarea=0 # enable hot areas (0: disable, 1: enable)

enable_floating_snap=1 # snap floating windows to edges or other windows
snap_distance=50 # max distance (pixels) to trigger floating snap
drag_tile_to_tile=1 # allow dragging a tiled window onto another to swap their positions