# https://mangowm.github.io/docs/window-management

# monitors
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:75,x:0,y:0,scale:1,vrr:1
monitorrule=name:eDP-1,width:3072,height:1920,refresh:120,x:1280,y:1080,scale:2,vrr:1

# workspaces
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# window rules
windowrule=tags:1,appid:footclient
windowrule=tags:2,appid:librewolf
windowrule=tags:3,appid:codium
windowrule=tags:4,appid:org.gnome.Nautilus
windowrule=tags:5,appid:org.telegram.desktop
windowrule=tags:6,appid:TrueConf
windowrule=tags:9,isfloating:1,appid:AmneziaVPN
windowrule=isfloating:1,appid:xfce-polkit
